# Site Info
title: A λ's Journey To Π 
tagline: ' Suggesting finite axioms for the infinite world.'
description: 'My personal website'
#baseurl: "" #/lanyon" # to be used when going for sub-directory  
url:  "https://rarchk.github.io" #"http://localhost:4000" # 
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
#  - jekyll-language-plugin
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 13
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0
#language_data: data.lang.hi
#language_includes_dir: _i18n

# About/contact
author:
  name: Ronak Kogta
  description: An engineer in the pursuit of <strong>persistent and exciting.</strong> Also trying to be a blogger.

  #gravatar:  # md5 hash of your email address
  profile: /public/images/profile.jpg
  contact:
    linkedin:  https://www.linkedin.com/in/ronakkogta
    github:    https://github.com/rarchk
    stack-overflow:    http://stackoverflow.com/users/733761/rarchk 
    twitter:   https://twitter.com/rarchk
    email:     https://www.google.com/recaptcha/mailhide/d?k\x3d01CIzJycu1pq2SHk5xVmq2RQ\x3d\x3d\x26c\x3dlBe-qtR3DTUeG_jldvPx-3bZV6esWSECuGNNBsZs9eA\x3d
    rss: /atom.xml
  
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:
    - /blog/
  Reflecitons:
    - /blog/reflections
  Projects:
    - /blog/projects

  Archive:
  - '/blog/archive'
  - { Categories: '/blog/categories/' }
  - { Tags: '/blog/tags/' }        



# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

#Quotes Project 
quotes: 
  Dead Poets Society: Listen, you hear it? — Carpe — hear it? — Carpe, carpe diem,
    seize the day boys, make your lives extraordinary.

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: #'UA-5613819-3' # leave blank if you don't want google analytics
disqus_short_name: #'rarchkgithubio' # leave blank if you don't want disqus

# posts to show at github
future: true

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
