# Site Info
title: A λ's Journey To Π 
tagline: 'Exploring finite axioms for the infinite world.'
description: 'Ronak Kogta personal blog'
#baseurl: "" #/lanyon" # to be used when going for sub-directory  
url:  "http://localhost:4000" #"https://rarchk.github.io" 
logo: '/public/logo.png'

# Site configurations
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 13
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0
#language_data: data.lang.hi
#language_includes_dir: _i18n

# About/contact
author:
  name: Ronak Kogta
  description: An engineer in the pursuit of <strong>persistent and exciting.</strong> Also trying to be a blogger.

  #gravatar:  # md5 hash of your email address
  profile: /public/images/profile.jpg
  contact:
    linkedin:  https://www.linkedin.com/in/ronakkogta
    github:    https://github.com/rarchk
    #stack-overflow:    http://stackoverflow.com/users/733761/rarchk 
    twitter:   https://twitter.com/ronakkogta
    #email:     https://www.google.com/recaptcha/mailhide/d?k\x3d01CIzJycu1pq2SHk5xVmq2RQ\x3d\x3d\x26c\x3dlBe-qtR3DTUeG_jldvPx-3bZV6esWSECuGNNBsZs9eA\x3d
    rss: /atom.xml
  
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:
    - /blog/
  Work:
    - /blog/work
  Reflecitons:
    - /blog/reflections

  Archive:
  - '/blog/archive'
  - { Categories: '/blog/categories/' }
  - { Tags: '/blog/tags/' }

  Github Issues:
    - https://github.com/rarchk/rarchk.github.io/issues/new
  Site Map v1.0.0:
    - /blog/sitemap.xml        



# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Plugins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-5613819-3' # leave blank if you don't want google analytics
#disqus_short_name: 'rarchkgithubio' # leave blank if you don't want disqus

# posts to show at github
future: true

# SEO Settings
seo:
  auto_generate_title: true
  auto_generate_description: true
  auto_generate_image: true
  twitter:
    username: ronakkogta
    card: summary_large_image
  facebook:
    app_id: # your fb app id if you have one
    publisher: # your fb page url
    admins: # your fb user id

# Performance Settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Content Settings
include: [".htaccess"]
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Alternate Format Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "**/*.txt"
    values:
      layout: "post.txt"
      permalink: /:year/:month/:day/:title.txt
  - scope:
      path: "**/*.md"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title.md

# Additional Plugin Settings
optional_front_matter:
  enabled: true
titles_from_headings:
  enabled: true
  strip_title: true
relative_links:
  enabled: true
  collections: true

# Optimization Settings
sass:
  style: compressed
  sourcemap: never
